<?php
?>
<div style="margin:auto;max-width:900px;padding: 50px 0 250px;">
<h3 style="text-align: center;">TERMS OF SERVICE, <?php echo date("Y"); ?> For our CUSTOMERS</h3>
<br>
<br>
<p style="text-align: center;">Have a question? Call us at 833-739-2273. We’d love to connect!</p>
<p style="text-align: center;">This TERMS OF SERVICE document (hereinafter “Terms”) is a legal document which describes your rights and obligations as an EZcard / EZ Digital customer. Last update, 3-20-20.</p>
<p style="text-align: center;">As a valued Customer, please read these Terms of Service. We promise you that we’ll try to keep it EZ!</p>
<p style="text-align: center;">Alas, we have to throw in some legal stuff too! We’ll try to interpret!</p>
    <br>
<p><b>WHO WE ARE?</b> EZ Digital LLC, a Texas Limited Liability Corporation (the “Company”), often known simply as “EZcard,” our trademarked product.</p>
<p><b>WHAT IS EZCARD?</b> EZcard is a software product that can be used as a “digital business card,” or a “smart-phone app,” or as a “mini website” for your phone. </p>
<p><b>WANT TO REACH US?</b> Have a question? Need to complain? Have a compliment? We love it all! Please visit our website, ezcard.com, or email us at help@ezcard.com, or call us at 833-729-2273.</p>
<p><b>READ THIS FIRST, PLEASE!</b> EZcard is committed to making your digital life EASIER. Please use our friendly A+ customer service! And if we ever disappoint you in any way, please let us know! We’ll do our best to FIX IT, whatever the problem is. Our goal is to take the Digital Overwhelm out of your life (as much as possible) – yes, including the avalanche of emails you get every day – and give you a way to share Your Important Messages with people, right on their smart phones. We carry our smart phones around with us pretty much EVERYWHERE. I’m sure you do too! That’s why we need something like EZcard. If you can type, upload an image, or call us for some help, we’ll get your message out!</p>
<p>EZcard relies on our proprietary software, trademark in hand, and copyrights and patents in process, to replace or supplement your paper business card, and to reduce all of the PAPERWORK that you might have relied on in the past. Let’s save some trees! And let’s do it in a way that gets people’s attention, and makes things easy for them! </p>
<p>TERMS OF SERVICE By using our software product and services, you are agreeing to the Terms of Service, “Terms,” contained in this document. If you do not agree, you should not use EZcard or any other products and services that we offer. </p>

<h4 style="font-size:19px;font-weight: bold;margin-top:25px;">TERMS & DEFINITIONS</h4>

<p><b>The Company.</b> This refers to EZ Digital LLC, registered in the State of Texas, referred to in this document as “The Company” or “Company” or “EZ Digital” or “EZcard” or “we” or “us” or “our.”</p>
<p><b>Customer.</b> This refers to one customer, or many customers, who pay for the EZcard on a subscription basis, whether monthly or yearly, or pay by any other basis, or use our services without pay by but permission. If refers to users of the online software at ezcard.com, and also users of our “app” (release date, early 2019) to be available from the App Store or Google Play Store, or users of any of our affiliated products and services.</p>
<p><b>User.</b> This refers to anyone that the Customer has allowed to access our software’s back office, or who can contribute any information, images, or resources to any EZcard or EZ Digital product or service. It also refers to anyone who uses the EZcard or EZcard App as a free or paid customer. In some cases, users of a subscription may be limited according to specific agreement, and a Customer may be asked to pay for additional users. Many users, however, will be “free users,” but will also be bound by the Terms herein expressed.</p>
<p><b>Company System.</b> This refers to any technology or method that EZ Digital uses, whether hardware, software, or human resource, to deliver any product to a Customer or User. It also refers to any company data or information, whether it pertains to a customer, user, staff member, or employee of EZ Digital. </p>
<p><b>Ownership.</b> This refers to the ownership of EZ Digital LLC technology, including but not limited to the EZcard, and any trademarks, patents or copyrights pertaining to Company software or technology, or intellectual property, including logos and artwork, and company content in writing, whether electronic or otherwise. Customers and users agree to not infringe on the ownership rights of anything owned by the Company.</p>
<p><b>Support.</b> This refers to our customer service offered as part of any product or service subscription, or beyond the scope of such subscriptions. We pledge to you the best customer service and support experience possible! Given that intention, we bear no responsibility or liability for errors made on your part, or on our part, which result in negative outcomes, including financial loss, or any other alleged harm, from alleged customer support.</p>
<p><b>Exclusions.</b> The Company bears no responsibility or liability for any Customer’s use of our products and services, whether such use is recommended or not, whether our product is used in modified or unmodified form, regarding any material or immaterial outcome of the use of our products and services, or the non-use of such services due to internet interruption or failed equipment or service, or human error. All outcomes related to the use of Company products and services are deemed to be the responsibility of the Customer or User. Customers and Users will make use of our product and the Company System with these exclusions in mind.</p>
<p><b>Communication.</b> This refers to any effort on our part to reach you as a Customer or potential Customer, or past Customer, or any effort on your part to reach us, whether successful or unsuccessful. You agree to be contacted by the Company with respect to your account and related purposes, and to receive emails and/or SMS messages, phone calls, MMS, and other communications as needed. You may opt out of such communications whenever you wish, as long as your account is paid and in good standing. </p>
<p><b>Customer Data / Personal Information.</b> This refers to information or data that is either public or private, regarding yourself personally, or your company that you may be advertising on EZ Digital technology. You agree to share with us personal information such as your legal name, address, phone number (including mobile number), your company name (if applicable), your title (if applicable), and your email, or multiple emails (if necessary), for the purpose of maintaining your account and services. This data will remain confidential, and will not be sold or given to other companies, except as expressly permitted by you, and for authorized internal marketing of EZcard’s products and services to you on an opt-in / opt-out basis. You agree to share with us appropriate financial and payment information to service your account and pay for rendered services. All credit card information is stored with a secure, third-party service, and is not stored on EZcard servers.</p>

<h4 style="font-size:19px;font-weight: bold;margin-top:25px;">Customer Responsibilities</h4>

<p><b>Payment.</b> All customers agree to pay for products and services requested and received, and to maintain updated financial information for their credit cards and other forms of payment for company records. When payment lapses for any reason, customers agree to make any payments in arrears to bring their account ledger up to date. When you purchase a monthly subscription, your credit card will usually be charged on the same day of the month as the day when you made your initial purchase. For an annual subscription, the annual payment will process on the same month and day as your initial purchase. When you subscribe to any of our products and services, you are agreeing to these recurring charges, and to keeping your payment sources current and valid. If you do not pay or keep payment current, you acknowledge that your service will be shut off or discontinued, and that after a reasonable period of time, your data will no longer be stored or available. Methods of payment may be changed at any time by the customer, but at least one valid credit card must be kept on file at all times of the account will be in danger of cancellation.</p>
<p><b>Grace Period.</b> After missing a payment, an account will be temporarily disabled and cannot be used until valid payment is made. However, Customers have up to and including 30 days to make a valid payment before an account is canceled.</p>
<p><b>Content.</b> EZcard is dedicated to providing wholesome content on all of its products and platforms, to empower and elevate people and communities, not to drag them down or degrade them, and users agree to only provide content that is educational, informational, inspirational, positive, or at least “neutral,” humorous or fun, useful, including any sales or marketing material helpful for running a business or an organization, and to refrain from posting anything that goes against your better judgment, or that is unwise or questionable, or that belongs to the following list. Specifically...</p>
<p>You Agree Not to Post Anything That is:</p>

<ul class="list-group">
    <li class="list-group-item">Illegal</li>
    <li class="list-group-item">Sexually explicit or pornographic</li>
    <li class="list-group-item">Obscene, or vulgar, profane, rude, obnoxious, or flagrantly insensitive</li>
    <li class="list-group-item">Divisive or promotes violence or civil unrest</li>
    <li class="list-group-item">Immoral or promotes immorality</li>
    <li class="list-group-item">Defamatory or negatively targets an individual or group</li>
    <li class="list-group-item">Deceptive</li>
    <li class="list-group-item">Has no social benefit</li>
    <li class="list-group-item">An Infringement on copyrighted material, or the intellectual property of others</li>
</ul>

<p><b>Links & Notices.</b> You agree not to create any hyperlink to another website or online source, from an EZcard or EZ Digital product, that is not compliant to the guidelines under Content. EZ Digital also takes no responsibility for any links to outside websites or online resources created by any Customer or User, and reserves the right to cancel any account for individuals who violate these stated guidelines. You agree to also notify EZ Digital when you see material on any EZcard or EZ Digital website which you believe violates these guidelines, to protect the prosocial nature of the EZcard platform, for the purposes of empowering individuals and elevating communities. Some large social media platforms like Facebook have many types of content, including both positive content and objectionable content that violates our standards, so while it is permissible to connect to a social page on Facebook or another larger and diverse platform, it is not permissible to connect to a specifically negative or objectionable site that violates our standards.</p>
<p><b>Cancelation.</b> Because we have development and design costs with EZcard, all initial payments and sales are final, including annual or yearly payments. You may cancel future charges at any time, for any reason. Cancelation of one product does not imply a cancelation of all products or services, and if you have signed up for services through any third parties, you may need to cancel with them as well. All cancelations must be submitted in writing by email to help@ezcard.com, but we will gladly help you with your cancelation if you call us. Your request will be dated as of the date of your email, and any refunds, etc., will be judged according to this date. Any payments or amount owed the Company still needs to be paid if you cancel, including any charges incurred to third-party vendors. Your cancelation request must include your legal name, your EZcard system ID, account email, address, your request to cancel, and the reason for your request. Only an account Owner, or another User designated as an Account Administrator, can cancel an account. Refunds will be processed within 30 days.</p>
<p><b>Authorized Access.</b> All customers will receive authorized access to any accounts for which they have paid, or to which they are otherwise entitled to access. You as a Customer agree to not access accounts to which you have not been granted access, nor will you gather or harvest any data or information from the Company or other Customers without their consent, or knowingly disrupt or degrade data or performance in any way that is not authorized, including but not limited to the destruction of data or elimination of accounts or information. You agree not to do anything that damages or degrades or disrupts the user experience of any other user, or of the Company or users in general. </p>
<p><b>Account Ownership & Access, User Assignment & Transferability.</b> Your account may transferred to another account Owner if the current Owner so requests, with appropriate identity verification, and you may also assign other Users of your account besides yourself, who can have various levels of account access, including all Administrative rights. </p>
<p><b>Annual Renewals.</b> Some products, but not all, may have annual renewal fees. All Customers should be aware of the renewal fees at the time of initial purchase. For instance, one option for EZcard hosting is to pay annually, usually for a savings of about two months of hosting. Customers should be aware that one year after the date of starting an account with the first payment, the annual renewal charge will be due and will be automatically charged to the credit card on record.</p>
<p><b>Product Changes.</b> Customers may change their product order at any time, including adding additional products and services. In the case of cancelations or downgrades, any refunds or credits issued are at the discretion of EZ Digital. We will definitely try to work with you to ensure you have the product package that best fits your needs! </p>
<p><b>Mission and Philosophy.</b> All Customers and Users of EZcard and EZ Digital products and services must accept and support the Company Mission and Philosophy, with respect to using our products and services. </p>
<p>The mission of EZ Digital LLC and EZcard, is to empower and elevate all people & communities with innovative digital communication. </p>
<p>See more of our Mission & Philosophy. </p>
<p><b>Logos, Artwork, Copyrights, and Intellectual Property.</b> You agree to use Company logos, artwork, and material only as approved and directed, and never to use copyrighted images that you don’t personally own, or for which you do not have a usage license, or explicit approval in writing, on an EZcard or EZcard platform. You agree that you are not an Agent of a competitor company to EZcard or EZ Digital LLC. If so, you must receive written permission to utilize our products and services, or agree not to use them or have access to them.</p>
<p>Data Privacy. You agree not to hack into company servers or mine company data you are not authorized to see or possess, to support such activities by another person or organization, or to use such information, if incidentally viewed or obtained, for personal profit or gain beyond what is permitted use within your private EZ Digital account, or within the approved Compensation plan. </p>
<p>You agree not to use, sell, or give private information about customers or EZ staff persons, for non-authorized marketing or commercial or private purposes, or those beyond what is allowed through EZcard and its approved marketing venues. </p>
<p><b>Modification of Terms.</b> We reserve the legal right, as stated here, to modify any of the terms and conditions in this Agreement at any time at our sole discretion. Any changes will be published to this document and available on our website, ezcard.com. Modifications may include, but are not limited to, changes in the Mission, Philosophy, and Terms of Service. If any change or modification is unacceptable to you, your only option is to end this Agreement. Your continued participation following any changes to the Agreement, as posted on our website, will indicate your agreement to the changes.</p>
<p><b>Confidentiality.</b> All confidential information, including, but not limited to, any business, technical, financial, and customer information, disclosed by one party to the other during the effective term of this Agreement which is marked or indicated to be "Confidential," will remain the sole property of the disclosing party, and each party will keep in confidence and not use or disclose such proprietary information of the other party without express written permission of the disclosing party.</p>
<p><b>Applicable Laws.</b> The laws of the State of Texas (the State of incorporation for EZ Digital LLC) will govern this Agreement, without reference to rules governing choice of laws. Any action relating to this Agreement must be brought in the federal or state courts located in Texas, and you irrevocably consent to the jurisdiction of such courts. </p>
<p><b>Accepting These Terms.</b> All Customers and Users of EZcard and EZ Digital products MUST ACCEPT ALL TERMS OF THIS AGREEMENT. IF YOU DO NOT ACCEPT THESE TERMS, YOU SHOULD NOT USE OUR PRODUCTS AND SERVICES.
</div>