apiVersion: v1
kind: Service
metadata:
  name: development-circle-service-dev
  namespace: circle-ci-k8s-dev
  labels:
    app: excell-circle-app-dev
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app: excell-app-dev
  type: LoadBalancer